// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_WITH_SECRET_START = 'AUTH_WITH_SECRET_START';
export const AUTH_WITH_SECRET_SUCCESS = 'AUTH_WITH_SECRET_SUCCESS';
export const AUTH_WITH_SECRET_FAIL = 'AUTH_WITH_SECRET_FAIL';
export const REFRESH_TOKEN_START = 'REFRESH_TOKEN_START';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK = 'AUTH_CHECK';

// Message
export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_HIDDEN = 'MESSAGE_HIDDEN';